[project]
name = "dem-height-nerfacto"
version = "0.1.0"
dependencies = ["nerfstudio", "rasterio"]

[project.entry-points."nerfstudio.method_configs"]
mountainnerf = "mountainnerf.dem_height_config:mountainnerf"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
